/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alarm;

import java.awt.Toolkit;
import java.text.DateFormat;
import java.time.Duration;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author samuthojo
 */
public class AlarmApp extends javax.swing.JFrame {

    /**
     * Creates new form AlarmApp
     */
    public AlarmApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarmDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alarmPanel = new javax.swing.JPanel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alarmLabel = new javax.swing.JLabel();

        alarmDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        alarmDialog.setTitle("Alarm Dialog");
        alarmDialog.setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        alarmDialog.setLocation(new java.awt.Point(450, 200));
        alarmDialog.setMinimumSize(new java.awt.Dimension(100, 100));
        alarmDialog.setSize(new java.awt.Dimension(300, 250));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hey! It's Time!");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alarmDialogLayout = new javax.swing.GroupLayout(alarmDialog.getContentPane());
        alarmDialog.getContentPane().setLayout(alarmDialogLayout);
        alarmDialogLayout.setHorizontalGroup(
            alarmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmDialogLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(alarmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addGroup(alarmDialogLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(12, 12, 12)
                        .addComponent(jButton3)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        alarmDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3});

        alarmDialogLayout.setVerticalGroup(
            alarmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmDialogLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alarmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        alarmDialog.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AlarmApp");
        setIconImage(Toolkit.getDefaultToolkit().getImage(AlarmApp.class.getResource("/alarm/resources/alarm"))
        );
        setLocation(new java.awt.Point(450, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        jSpinner2.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner2, "HH:mm "));

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ALARM:");

        alarmLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alarmLabel.setVisible(false);
        String b = new StringBuilder(String.valueOf(jSpinner2.getValue())).substring(11, 19);

        DateTimeFormatter tf = DateTimeFormatter.ofPattern("H:mm:ss");

        LocalTime t = LocalTime.parse(b, tf);

        LocalTime n = LocalTime.now();

        long s = Duration.between(n, t).getSeconds();

        int m = (s >= 3600) ? (int)(s % 3600) : (int)(s / 60);

        int h = (int) (s / 3600);
        alarmLabel.setText(AlarmApp.printDur(h, m));

        javax.swing.GroupLayout alarmPanelLayout = new javax.swing.GroupLayout(alarmPanel);
        alarmPanel.setLayout(alarmPanelLayout);
        alarmPanelLayout.setHorizontalGroup(
            alarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarmPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(alarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(alarmLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        alarmPanelLayout.setVerticalGroup(
            alarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(alarmLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alarmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("jFrame1");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static javax.swing.JFrame frame = new AlarmApp();

    static AlarmTask alarmTask;

    //Done button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        (alarmTask = new AlarmTask()).execute();
        frame.setVisible(false);
        AlarmTrayIcon.createGUI();
        
        /*alarmLabel.setVisible(true);
        Timer t = new Timer(800, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                alarmLabel.setVisible(false);
                frame.setVisible(false);
                AlarmTrayIcon.createGUI();
            }
        });
        t.setRepeats(false);
        t.start();*/
    }//GEN-LAST:event_jButton1ActionPerformed

    //Cancel button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        alarmDialog.dispose();
        showDialog();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Reset button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cancel();
        alarmDialog.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        showDialog();
    }//GEN-LAST:event_formWindowClosing

    public static void showDialog() {
        int response = JOptionPane.showConfirmDialog(frame, "Do you want to exit AlarmApp?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == 0) {
            close();
        } else {
            frame.setVisible(true);
        }
    }

    public static void cancel() {
        alarmTask.cancel(true);
        alarmTask = null;
    }

    public static javax.swing.JDialog getDialog() {
        return alarmDialog;
    }

    public static String printDur(int h, int m) {
        /*String s;
        if (h > 0 && m > 0) {
            s = String.format((h > 1) ? "Alarm set for %d hours and %d minutes from now%n" : "Alarm set for %d hour and %d minutes from now%n", h, m);
        } else if (h > 0 && m == 0) {
            s = String.format((h > 1) ? "Alarm set for %d hours from now%n" : "Alarm set for %d hour from now%n", h);
        } else if (h < 1 || m > 0) {
            s = String.format((m >= 1) ? "Alarm set for %d minute(s) from now%n" : "Alarm set for less than 1 minute from now%n" , m);
        } else {
            s = String.format("Alarm set for less than 1 minute from now%n");
        }
        return s;*/
        return "";
    }

    //Background task: monitoring the time
    private class AlarmTask extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() {
            DateFormat k;

            k = DateFormat.getTimeInstance(DateFormat.DEFAULT, Locale.GERMAN);

            String b = new StringBuilder(String.valueOf(jSpinner2.getValue())).substring(11, 19);

            while (!(k.format(new Date())).equals(b)) {
                ;
            }
            return null;
        }

        @Override
        public void done() {
            alarmDialog.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame.setVisible(true);
            }
        });

    }

    public static void close() {
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDialog alarmDialog;
    private javax.swing.JLabel alarmLabel;
    private javax.swing.JPanel alarmPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
